import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {Game} from '../src/game.js';import {Navigation,Random,defaultProfile,cleanProfile,MODS,NODE_RELICS,prereq,nodeCost} from '../src/rules.js';
const data=JSON.parse(fs.readFileSync(new URL('../public/content/manifest.json',import.meta.url),'utf8').replace(/^\uFEFF/,''));
const newGame=(loadout=0)=>{const p=defaultProfile();p.loadout=loadout;const g=new Game(data,p);g.start(4217);g.readyRoom([],[]);g.events=[];return g;};
test('seeded rolls reproduce System.Random fixture',()=>{const r=new Random(1);assert.equal(r.next(2147483647),534011718);assert.equal(r.next(2147483647),237820880);assert.equal(r.next(2147483647),1002897798);});
test('profile input is bounded and duplicates cannot grant extra training',()=>{const p=cleanProfile({version:1,bank:-2,vitality:30,skills:[0,0,35,-1,'7'],weapons:[20,-4],loadout:9});assert.deepEqual(p.skills,[0,35]);assert.equal(p.bank,0);assert.equal(p.vitality,5);assert.deepEqual(p.weapons,[3,0,0,0,0,0]);});
test('cover blocks bullets, walking slides, path routes around it',()=>{const n=new Navigation([{x0:-.5,x1:.5,z0:-.5,z1:.5}]),a={x:0,z:2},b={x:0,z:-2};assert.equal(n.clear(a,b),false);const route=n.path(a,b);assert.ok(route.length>1);let p={...a};for(let i=0;i<2000&&route.length;i++){const t=route[0],d=Math.hypot(t.x-p.x,t.z-p.z);if(d<.15)route.shift();else n.move(p,(t.x-p.x)/d*.05,(t.z-p.z)/d*.05);assert.equal(n.free(p.x,p.z),true);}assert.ok(Math.hypot(p.x-b.x,p.z-b.z)<.2);});
test('all three loadouts start with their weapon, skill and relics',()=>{for(let i=0;i<3;i++){const g=newGame(i);assert.equal(g.weapon,[0,4,5][i]);assert.equal(g.skill,[0,2,1][i]);assert.ok(g.owned[0]&&g.owned[1]);assert.equal(g.S[[7,11,31][i]],1);}});
test('36 training nodes honor tier prerequisites and apply only selected discipline',()=>{const p=defaultProfile();p.bank=10000;const g=new Game(data,p);assert.equal(g.trainNode(3),false);for(let i=0;i<36;i++)assert.equal(g.trainNode(i),true);assert.equal(g.trainNode(0),false);g.start(7);for(let i=0;i<12;i++)assert.ok(g.S[NODE_RELICS[i]]>=1);assert.equal(g.S[2],0);assert.equal(g.trainNode(1),false);});
test('all 18 mastery tiers have increasing costs and grant once on acquisition',()=>{for(let w=0;w<6;w++){const p=defaultProfile();p.bank=1000;const g=new Game(data,p);for(let t=0;t<3;t++)assert.equal(g.trainWeapon(w),true);assert.equal(p.bank,795);assert.equal(g.trainWeapon(w),false);g.start(42);if(w>=2){assert.ok(!g.granted[w]);g.apply(w+16);}const before=[...g.S];for(const id of MODS[w])assert.ok(g.S[id]>0);g.grantTraining(w);assert.deepEqual(g.S,before);}});
test('drafts are unique, respect caps, and use supplies only when exhausted',()=>{const g=newGame();for(let n=0;n<500;n++){const ids=g.draft(n%2===0);assert.equal(new Set(ids).size,3);ids.forEach(i=>assert.ok(g.canTake(i)));g.apply(ids[0]);}g.stacks=data.relics.map(d=>d.cap);g.heartSpent=false;assert.deepEqual(g.draft().sort(),[60,61,62]);});
test('rerolls deduct atomically and cannot exceed two',()=>{const g=newGame();g.scrap=19;g.offer();assert.equal(g.reroll(),true);assert.equal(g.scrap,11);assert.equal(g.reroll(),false);g.scrap=12;assert.equal(g.reroll(),true);g.scrap=100;assert.equal(g.reroll(),false);});
test('fabricator spends depth-scaled salvage once and bonus draft preserves the room',()=>{const g=newGame();g.scrap=9;g.interactables=[{x:g.player.x,z:g.player.z,kind:3,used:false}];assert.equal(g.interact(),false);assert.equal(g.scrap,9);g.scrap=10;assert.equal(g.interact(),true);assert.equal(g.scrap,0);assert.equal(g.rewardsRemaining,1);g.choose(0);assert.equal(g.screen,null);assert.equal(g.room,1);assert.ok(g.interactables[0].used);});
test('all weapons hit valid targets and solid cover stops their primary hit',()=>{for(let w=0;w<6;w++){const g=newGame();g.weapon=w;g.player.x=0;g.player.z=1.4;g.enemies=[];const e=g.spawnEnemy('BrassConstable',{x:0,z:0},false,false,100);g.fire({x:0,z:0});assert.ok(e.hp<e.maxHP,'weapon '+w);const hp=e.hp;g.player.attackCD=0;g.nav=new Navigation([{x0:-1,x1:1,z0:.5,z1:.7}]);g.fire({x:0,z:0});assert.equal(e.hp,hp,'blocked weapon '+w);}});
test('burst receiver produces exactly two non-primary delayed shots',()=>{const g=newGame();g.enemies=[];g.player.x=0;g.player.z=2;const e=g.spawnEnemy('BrassConstable',{x:0,z:0},false,false,100);g.apply(48);g.fire(e);assert.equal(g.delayed.length,2);for(let i=0;i<8;i++)g.update(.03,{move:{x:0,z:0},aim:e,fire:false});assert.equal(g.delayed.length,0);assert.ok(e.hp<=e.maxHP-3);});
test('dash has invulnerability, cooldown, barrier and wake effects',()=>{const g=newGame();g.apply(25);g.apply(26);g.apply(38);const hp=g.player.hp;assert.ok(g.dash({x:1,z:0}));assert.equal(g.barrier,8);assert.equal(g.fields.length,1);g.hurt(50);assert.equal(g.player.hp,hp);assert.equal(g.dash({x:1,z:0}),false);});
test('pause freezes combat timers, projectiles, enemies and fields',()=>{const g=newGame();g.skillCast();g.screen='pause';const state=JSON.stringify({time:g.time,p:g.player,enemies:g.enemies,fields:g.fields});g.update(.05);assert.equal(JSON.stringify({time:g.time,p:g.player,enemies:g.enemies,fields:g.fields}),state);});
test('tithe is once per expedition and costs maximum vitality',()=>{const g=newGame();g.offer();assert.ok(g.openTithe());assert.ok(g.acceptTithe());assert.equal(g.maxHP,85);assert.equal(g.openTithe(),false);assert.equal(g.profile.vitality,0);});
test('second heart revives once and barrier absorbs before vitality',()=>{const g=newGame();g.apply(17);g.giveBarrier(20,8);g.hurt(12);assert.equal(g.player.hp,100);assert.equal(g.barrier,8);g.hurt(1000);assert.equal(g.player.hp,40);assert.equal(g.heartSpent,true);g.hurt(1000);assert.equal(g.screen,'results');});
test('Null Pontiff shields, half-health anchors, defeat and deeper cycle retain build',()=>{const g=newGame();g.enter(5,4);g.readyRoom([],[]);g.enemies=[];const b=g.spawnEnemy('NullPontiff',{x:0,z:-1},true,false,48);g.anchors(3);assert.equal(g.hit(b,100),false);assert.equal(b.hp,b.maxHP);g.alive.filter(e=>e.anchor).forEach(e=>g.hit(e,100));g.hit(b,100);assert.equal(b.hp,Math.ceil(b.maxHP/2));assert.equal(g.alive.filter(e=>e.anchor).length,2);g.alive.filter(e=>e.anchor).forEach(e=>g.hit(e,100));g.hit(b,100);assert.equal(b.hp,0);g.apply(18);const stacks=[...g.S];assert.ok(g.descend());assert.equal(g.cycle,2);assert.deepEqual(g.S,stacks);assert.equal(g.weapon,2);g.readyRoom([],[]);assert.ok(g.alive.every(e=>e.affix>0));});
test('extraction requires the engine and settlement cannot pay twice',()=>{const g=newGame();g.enter(5,4);g.readyRoom([],[]);g.enemies.filter(e=>e.anchor).forEach(e=>g.hit(e,100));const b=g.boss;b.name='CenserKingBody';g.hit(b,1000);assert.equal(g.extract(),false);const ex=data.rooms[5].extraction;g.player.x=ex[0];g.player.z=ex[2];g.scrap=20;g.drops=[];assert.ok(g.extract());assert.equal(g.profile.bank,50);g.settle(true);assert.equal(g.profile.bank,50);});
test('complete two-cycle route sequence offers two picks per district',()=>{const g=newGame();for(let cycle=1;cycle<=2;cycle++){for(let room=1;room<=3;room++){assert.equal(g.room,room);for(const e of [...g.alive])g.hit(e,10000);assert.equal(g.screen,'rewards');g.choose(0);assert.equal(g.screen,'rewards');g.choose(0);if(room<3){assert.equal(g.screen,'route');g.selectRoute(cycle%2);g.readyRoom([],[]);}else g.readyRoom([],[]);}const b=g.boss;b.name='BellMother';g.alive.filter(e=>e.anchor).forEach(e=>g.hit(e,100));g.hit(b,10000);if(cycle===1){assert.ok(g.descend());g.readyRoom([],[]);}else{const ex=data.rooms[5].extraction;g.player.x=ex[0];g.player.z=ex[2];assert.ok(g.extract());}}assert.equal(g.upgrades,12);assert.equal(g.bossesDefeated,2);assert.equal(g.screen,'results');});



test('navigation snaps a free edge position to a reachable grid cell',()=>{const n=new Navigation([{x0:1.5811,x1:2.5111,z0:-1.9132,z1:-.8132}]);const start={x:2.2935,z:-2.2542};assert.ok(n.free(start.x,start.z,.28));assert.ok(n.path(start,{x:0,z:2.75}).length>1);});
test('skirmishers dodge sustained aim instead of remaining stationary',()=>{const g=newGame();g.enemies=[];g.player.x=0;g.player.z=2;const e=g.spawnEnemy('SpoolAssassin',{x:0,z:0},false,false,80);e.seed=0;e.attackCD=100;e.decision=100;e.destination={x:0,z:0};for(let i=0;i<12;i++){g.time+=.04;g.updateEnemy(e,.04,{fire:true,aim:{x:e.x,z:e.z}});}assert.ok(e.dodge>0);assert.ok(e.destination.x!==0);});
test('death banks only already-collected salvage and discards loose drops',()=>{const g=newGame();g.scrap=21;g.drops=[{x:4,z:4,amount:100,healing:false,id:500}];g.hurt(9999);assert.equal(g.profile.bank,10);});
