import {cleanProfile,WEAPONS,MODS,NODE_NAMES,NODE_RELICS,nodeCost,prereq,weaponCost,CONDITIONS,TRAITS} from './rules.js';
import {THREE} from './assets.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const btn=(action,text,extra='')=>'<button data-action="'+action+'" '+extra+'>'+text+'</button>';
const tier=i=>['REFINED','RARE','LEGENDARY'][i];
export class UI {
 constructor(game,world,audio){this.game=game;this.world=world;this.audio=audio;this.root=document.querySelector('#ui');this.hud=document.querySelector('#hud');this.tab=0;this.branch=game.loadout;this.weaponTab=0;this.ledgerPage=0;this.lastKey='';this.helpTab=0;this.returnPage='home';this.root.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;this.audio.unlock();this.audio.play('ui');this.action(b.dataset.action);});this.hud.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)this.action(b.dataset.action);});this.root.addEventListener('input',e=>{const k=e.target.dataset.setting;if(k){game.profile.settings[k]=e.target.type==='checkbox'?e.target.checked:e.target.type==='range'?Number(e.target.value):e.target.value;game.save();this.audio.settings=game.profile.settings;if(k==='quality')world.applyQuality();const label=e.target.parentNode.querySelector('output');if(label)label.textContent=Math.round(e.target.value*100)+'%';}});}
 action(action){const g=this.game,[a,value]=action.split(':'),i=Number(value);
  if(a==='start'){g.start(Number(document.querySelector('#seed')?.value)||undefined);}
  if(a==='loadout'){g.loadout=i;g.profile.loadout=i;g.save();}
  if(a==='page'){if(value==='pause'||value==='ledger'){this.returnPage=g.screen;g.screen=value;}else{this.returnPage=g.started?'pause':'home';g.screen=value;}this.tab=0;}
  if(a==='resume'){g.screen=this.returnPage&&['rewards','route','tithe'].includes(this.returnPage)?this.returnPage:null;}
  if(a==='back'){g.screen=g.started?'pause':'home';}
  if(a==='title'){g.toHome();}
  if(a==='branch')this.branch=i;if(a==='train')g.trainNode(i);if(a==='weaponTab')this.weaponTab=i;if(a==='trainWeapon')g.trainWeapon(i);if(a==='vitality')g.trainVitality();if(a==='choose')g.choose(i);if(a==='route')g.selectRoute(i);if(a==='reroll')g.reroll();if(a==='tithe')g.openTithe();if(a==='acceptTithe')g.acceptTithe();if(a==='declineTithe')g.screen='rewards';if(a==='ledgerPage')this.ledgerPage=i;if(a==='equip')g.switchWeapon(i);if(a==='helpTab')this.helpTab=i;if(a==='descend')g.descend();if(a==='fullscreen'){if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen().catch(()=>g.notice('Fullscreen is unavailable in this browser panel.'));}
  if(a==='restore'&&!g.started){const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{try{const file=input.files[0];if(!file)return;if(file.size>65536)throw Error('This file is too large for a game save.');const raw=JSON.parse(await file.text());if(raw.version!==1||!Number.isFinite(raw.bank)||!Array.isArray(raw.skills))throw Error('Choose a Neon Requiem browser save.');try{localStorage.setItem('NeonRequiem.Three.PreviousProfile',JSON.stringify(g.profile));}catch{}Object.assign(g.profile,cleanProfile(raw));g.loadout=g.profile.loadout;g.save();this.audio.settings=g.profile.settings;this.world.applyQuality();g.notice('BROWSER SAVE RESTORED');this.render(true);}catch(e){g.notice(e.message);}};input.click();}
  if(a==='export'){const blob=new Blob([JSON.stringify(g.profile,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='NeonRequiem-Web-Save.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  this.lastKey='';this.render();
 }
 escape(){const g=this.game;if(!g.started){g.screen=g.screen==='home'?'home':'home';}else if(g.screen==='pause')g.screen=this.returnPage&&['rewards','route','tithe'].includes(this.returnPage)?this.returnPage:null;else if(['settings','help','ledger'].includes(g.screen))g.screen='pause';else if(g.screen==='tithe')g.screen='rewards';else if(g.screen!=='results'&&g.screen!=='travel'){this.returnPage=g.screen;g.screen='pause';}this.lastKey='';}
 card(id,action){const g=this.game,d=g.data.relics[id];return '<button class="relic tier'+d.tier+'" data-action="'+action+'"><span class="eyebrow">'+tier(d.tier)+' / '+esc(d.family)+'</span><span class="relic-sigil">'+['✧','❖','◈'][d.tier]+'</span><h2>'+esc(d.name)+'</h2><p>'+esc(d.description)+'</p><span class="card-foot">'+(id>=60?'IMMEDIATE SUPPLY':'STACK '+g.S[id]+' → '+(id===17?1:g.S[id]+1)+' / '+d.cap)+'</span></button>';}
 frame(title,sub,body,footer=''){return '<section class="panel"><header><div><p class="eyebrow">'+sub+'</p><h1>'+title+'</h1></div>'+btn('back','← Back','class="quiet"')+'</header>'+body+(footer?'<footer>'+footer+'</footer>':'')+'</section>';}
 render(force=false){const g=this.game,key=[g.screen,g.profile.bank,g.profile.skills.join(','),g.profile.weapons.join(','),g.weapon,g.choices?.join(','),g.rewardsRemaining,g.scrap,this.branch,this.weaponTab,this.ledgerPage,this.helpTab,g.titheUsed].join('|');
 if(force||key!==this.lastKey){this.lastKey=key;let html='';const bank='<span class="bank">◈ '+g.profile.bank+' <small>BANKED SALVAGE</small></span>';
 if(g.screen==='home')html='<section class="home"><p class="eyebrow">NEW BABEL • THE LIVING CITY</p><img class="logo" src="./brand/logo.png" alt="Neon Requiem"><p class="intro">Steel remembers. The city never forgives.</p><div class="loadouts">'+g.data.loadouts.map((n,i)=>'<button class="loadout '+(g.loadout===i?'selected':'')+'" data-action="loadout:'+i+'"><span>'+['Ⅰ','Ⅱ','Ⅲ'][i]+'</span><h3>'+esc(n.replace('THE ',''))+'</h3><p>'+['Precision & momentum','Fire & reclamation','Lightning & control'][i]+'</p></button>').join('')+'</div><p class="loadout-detail">'+esc(g.data.loadoutDetails[g.loadout].split('\n').slice(0,3).join(' · '))+'</p>'+btn('start','Begin Expedition <span>↗</span>','class="primary begin"')+'<div class="menu-row">'+btn('page:workshop','Workshop')+btn('page:help','Field Guide')+btn('page:settings','Settings')+'</div><div class="home-foot">'+bank+'<label>RUN SEED <input id="seed" inputmode="numeric" type="number" placeholder="Random"></label></div><p class="edition">THREE.JS EDITION • DESKTOP / KEYBOARD & MOUSE</p></section>';
 if(g.screen==='workshop')html=this.frame('The Workshop','PERSISTENT TRAINING / '+g.data.loadouts[g.loadout],'<div class="workshop-intro">'+bank+'<p>Earn salvage in the city. Extract to bank it all. Train before your next expedition.</p></div><div class="menu-row">'+btn('page:skills','Discipline Trees','class="primary"')+btn('page:weapons','Weapon Mastery','class="primary"')+'</div><div class="upgrade-block"><div><h2>Steel Constitution</h2><p>+10 starting vitality per rank. Current rank '+g.profile.vitality+' / 5.</p></div>'+btn('vitality',g.profile.vitality===5?'Fully trained':'Train · '+(25+15*g.profile.vitality)+' salvage',(g.started||g.profile.vitality>=5||g.profile.bank<25+15*g.profile.vitality)?'disabled':'')+'</div>');
 if(g.screen==='skills'){const body='<div class="tabs">'+g.data.loadouts.map((n,i)=>btn('branch:'+i,esc(n),'class="'+(this.branch===i?'selected':'')+'"')).join('')+bank+'</div><p class="explain">Viewing '+esc(g.data.loadouts[this.branch])+'. Only your starting discipline applies this run. Each node requires the node directly above it.</p><div class="tree">'+Array.from({length:12},(_,j)=>{const id=this.branch*12+j,rid=NODE_RELICS[id],owned=g.profile.skills.includes(id),locked=prereq(id)>=0&&!g.profile.skills.includes(prereq(id)),can=!g.started&&!owned&&!locked&&g.profile.bank>=nodeCost(id);return '<button class="node '+(owned?'trained ':'')+(locked?'locked':'')+'" data-action="train:'+id+'" '+(can?'':'disabled')+'><span class="eyebrow">TIER '+(Math.floor(j/3)+1)+' / '+(owned?'TRAINED':locked?'PREREQUISITE REQUIRED':nodeCost(id)+' SALVAGE')+'</span><h3>'+NODE_NAMES[id]+'</h3><p>'+esc(g.data.relics[rid].description)+'</p></button>';}).join('')+'</div>';html=this.frame('Discipline Trees','36 TRAINING NODES / '+bank,body);}
 if(g.screen==='weapons'){const w=this.weaponTab,rank=g.profile.weapons[w];html=this.frame('The Gunsmith','WEAPON MASTERY / '+bank,'<div class="tabs weapon-tabs">'+WEAPONS.map((n,i)=>btn('weaponTab:'+i,n,'class="'+(i===w?'selected':'')+'"')).join('')+'</div><p class="explain">Training grants these mods once when you acquire this weapon during an expedition.</p><div class="mastery">'+MODS[w].map((id,t)=>'<article class="mastery-card '+(rank>t?'trained':'')+'"><span class="eyebrow">TIER '+(t+1)+' / '+(rank>t?'TRAINED':weaponCost(t)+' SALVAGE')+'</span><div class="relic-sigil">'+['Ⅰ','Ⅱ','Ⅲ'][t]+'</div><h2>'+esc(g.data.relics[id].name)+'</h2><p>'+esc(g.data.relics[id].description)+'</p>'+btn('trainWeapon:'+w,rank>t?'Trained':rank===t?'Train this tier':'Train previous tier',rank===t&&!g.started&&g.profile.bank>=weaponCost(t)?'class="primary"':'disabled')+'</article>').join('')+'</div>');}
 if(g.screen==='pause')html='<section class="pause panel"><p class="eyebrow">SIGNAL HELD / EXPEDITION PAUSED</p><h1>A Moment in the Rain</h1>'+btn('resume','Resume Expedition','class="primary"')+btn('page:ledger','Build Ledger')+btn('page:help','Field Guide')+btn('page:settings','Settings')+btn('title','Abandon Run & Return to Title','class="quiet"')+'<p class="muted">Unbanked salvage is lost when abandoning a run.</p></section>';
 if(g.screen==='rewards')html='<section class="rewards"><p class="eyebrow">RELIQUARY OPENED / DEPTH '+g.depth+'</p><h1>Choose Your Inheritance</h1><p class="sub">'+g.rewardsRemaining+' '+(g.rewardsRemaining===1?'choice':'choices')+' remaining · Your build carries into every deeper cycle.</p><div class="cards">'+g.choices.map((id,i)=>this.card(id,'choose:'+i)).join('')+'</div><div class="reward-foot"><span>◈ '+g.scrap+' RUN SALVAGE</span>'+btn('reroll','Reroll · '+(8+g.rewardRerolls*4)+' salvage',g.rewardRerolls>=2||g.scrap<8+g.rewardRerolls*4?'disabled':'')+btn('tithe',g.titheUsed?'Tithe Accepted':'Memory Tithe · G',g.titheUsed||g.maxHP<=35?'disabled':'')+btn('page:ledger','Inspect Build')+'</div></section>';
 if(g.screen==='route')html='<section class="rewards"><p class="eyebrow">EXPEDITION / DEPTH '+(g.depth+1)+'</p><h1>Choose Your Route</h1><p class="sub">'+g.history.map(i=>esc(g.data.rooms[i].title)).join(' → ')+'</p><div class="routes">'+g.routeChoices.map((id,i)=>{const r=g.data.rooms[id];return '<button class="route-card district'+id+'" data-action="route:'+i+'"><span class="eyebrow">ROUTE 0'+(i+1)+'</span><div class="route-symbol">'+['','♨','◈','⌘','✧'][id]+'</div><h2>'+esc(r.title)+'</h2><p>'+esc(r.subtitle)+'</p><p class="danger">'+esc(r.danger)+'</p><p class="gold">'+esc(r.reward)+'</p><span class="card-foot">ENTER DISTRICT →</span></button>';}).join('')+'</div></section>';
 if(g.screen==='travel')html='<section class="travel"><p class="eyebrow">DESCENDING INTO NEW BABEL</p><h1>'+esc(g.data.rooms[g.roomIndex].title)+'</h1><p>Preparing the district…</p></section>';
 if(g.screen==='tithe')html='<section class="pause panel"><p class="eyebrow">A MEMORY FOR A MIRACLE</p><h1>The Memory Tithe</h1><h2 class="gold">'+esc(g.data.relics[g.titheOffer].name)+'</h2><p>'+esc(g.data.relics[g.titheOffer].description)+'</p><p class="danger">Surrender 15 maximum vitality<br>'+g.maxHP+' → '+(g.maxHP-15)+' for this expedition.</p>'+btn('acceptTithe','Accept the Bargain','class="primary"')+btn('declineTithe','Keep My Memory')+'</section>';
 if(g.screen==='ledger'){const owned=g.S.map((n,i)=>({n,i})).filter(x=>x.n),page=Math.min(this.ledgerPage,Math.max(0,Math.ceil(owned.length/6)-1));html=this.frame('The Build Ledger','EXPEDITION / DEPTH '+g.depth+' · CYCLE '+g.cycle,'<div class="stats"><span>VITALITY <b>'+g.player.hp+' / '+g.maxHP+'</b></span><span>BASE DAMAGE <b>'+g.damage+'</b></span><span>ATTACKS / SEC <b>'+(1/g.interval).toFixed(2)+'</b></span><span>CRITICAL <b>'+Math.round(g.crit*100)+'%</b></span><span>ARMOR <b>'+g.S[6]*2+'</b></span><span>SALVAGE <b>'+g.scrap+'</b></span></div><div class="tabs weapon-tabs">'+WEAPONS.map((n,i)=>btn('equip:'+i,n,'class="'+(g.weapon===i?'selected':'')+'" '+(!g.owned[i]?'disabled':''))).join('')+'</div><div class="ledger-list">'+owned.slice(page*6,page*6+6).map(({n,i})=>'<article><span class="stack">×'+n+'</span><h3>'+esc(g.data.relics[i].name)+'</h3><p>'+esc(g.data.relics[i].description)+'</p></article>').join('')+'</div><div class="pagination">'+btn('ledgerPage:'+Math.max(0,page-1),'← Previous',page===0?'disabled':'')+'<span>PAGE '+(page+1)+' / '+Math.max(1,Math.ceil(owned.length/6))+'</span>'+btn('ledgerPage:'+(page+1),'Next →',(page+1)*6>=owned.length?'disabled':'')+'</div>',btn('resume','Return to Expedition','class="primary"'));}
 if(g.screen==='results')html='<section class="pause panel"><p class="eyebrow">'+(g.victory?'MEMORIES RECLAIMED':'SIGNAL LOST')+'</p><h1>'+(g.victory?'The City Remembers':'Another Ghost in the Rain')+'</h1><p>'+ (g.victory?'All salvage secured, including '+30*g.cycle+' extraction bonus.':'Half of your collected salvage was recovered.')+'</p><div class="result-value">+'+g.banked+' <small>BANKED SALVAGE</small></div><p>Depth '+g.depth+' · '+g.bossesDefeated+' bosses defeated · '+g.upgrades+' relics chosen</p><p class="muted">'+g.history.map(i=>esc(g.data.rooms[i].title)).join(' → ')+'</p>'+btn('title','Return to the Workshop','class="primary"')+'</section>';
 if(g.screen==='settings'){const s=g.profile.settings;html=this.frame('Settings','PRESENTATION / AUDIO / LOCAL SAVE','<div class="settings-grid"><div><h2>Sound</h2>'+['master','effects','ambience','music'].map(k=>'<label class="slider">'+k+'<output>'+Math.round(s[k]*100)+'%</output><input aria-label="'+k+' volume" data-setting="'+k+'" type="range" min="0" max="1" step=".01" value="'+s[k]+'"></label>').join('')+'</div><div><h2>Presentation</h2><label class="setting">Rendering quality<select data-setting="quality"><option '+(s.quality==='high'?'selected':'')+'>high</option><option '+(s.quality==='balanced'?'selected':'')+'>balanced</option><option '+(s.quality==='low'?'selected':'')+'>low</option></select></label><label class="setting">Atmospheric motion<input data-setting="motion" type="checkbox" '+(s.motion?'checked':'')+'></label><label class="setting">Damage numbers<input data-setting="numbers" type="checkbox" '+(s.numbers?'checked':'')+'></label>'+btn('fullscreen','Toggle Fullscreen')+'<p class="muted">High: shadows and bloom. Lower quality reduces GPU load.</p></div></div><div class="save-row">'+btn('export','Back Up Browser Save')+btn('restore','Restore Backup',g.started?'disabled':'')+'<p>Training is saved in this browser. The Unity save is separate. Active expeditions do not survive a page reload.</p></div>');}
 if(g.screen==='help'){const titles=['Controls','Combat','Builds & Relics','The Expedition'],pages=[
 '<div class="controls">'+[['W A S D','Move relative to the camera'],['RIGHT MOUSE','Travel to a point around cover'],['LEFT MOUSE','Aim and fire your equipped weapon'],['SHIFT / SPACE','Sprint / invulnerable dash'],['TAB / F','Cycle owned weapons / active skill'],['E / N','Interact or extract / descend after boss'],['I / G','Build ledger / memory tithe at rewards'],['Q / ALT + E','Orbit camera'],['SCROLL / C','Zoom / toggle camera follow'],['ESC','Pause, help and settings']].map(([k,v])=>'<kbd>'+k+'</kbd><p>'+v+'</p>').join('')+'</div>',
 '<h2>Read the machinery. Watch the wind-up.</h2><p>Amber circles mark incoming strikes. Dashed aim lines warn of ranged attacks. Dodge out before the attack lands. Only two ordinary foes can commit to attacks at the same time.</p><p>Crates, tanks and district walls stop shots. Enemies flank and withdraw; skirmishers dodge sustained aim. Use solid cover to interrupt their sightline.</p><p>Surging foes move and attack faster. Armored foes withstand more damage. Regenerating foes recover vitality. Volatile corpses explode.</p><p>The Null Pontiff is shielded by violet anchors. Destroy the anchors before attacking him; he summons another set at half vitality.</p>',
 '<h2>Every stack changes the next decision.</h2><p>Six weapons, three active skills, sixty relics, thirty-six discipline nodes and eighteen weapon mastery tiers. Weapon mods are specific to their weapon; most other relics carry across your arsenal.</p><p>Clear a district to choose two relics. Each selection is one of three cards. Reroll up to twice for 8 then 12 run salvage. Fabricators offer an extra choice for a cost that rises with depth.</p><p>Chill, burn, poison, critical strikes, barriers and kill-triggered effects can combine. Read each card for stack limits and tradeoffs. The Memory Tithe trades 15 maximum vitality for a revealed legendary relic once per run.</p>',
 '<h2>Extract, invest, return stronger.</h2><p>Clear the Rainworks, choose one of two second districts, choose a third district, then face a boss in the Choir Throne.</p><p>After the boss falls, approach the cyan memory engine and press E to bank all salvage plus 30 per cycle. Press N to keep your entire build, recover 20 vitality and face a harder cycle with new cover layouts and enemy traits.</p><p>Death banks half your collected salvage. Spend banked salvage in the Workshop before a new run. Enemy health, hostile damage, rewards and fabrication costs rise as you descend.</p><p>All progression currency is earned by playing. There are no purchases, advertisements or microtransactions.</p>'
 ];html=this.frame('The Field Guide','KNOWLEDGE FOR THE DESCENT','<div class="tabs">'+titles.map((t,i)=>btn('helpTab:'+i,t,'class="'+(this.helpTab===i?'selected':'')+'"')).join('')+'</div><div class="help-content">'+pages[this.helpTab]+'</div>');}
 this.root.innerHTML=html;this.root.classList.toggle('open',!!g.screen);document.body.classList.toggle('menu-open',!!g.screen);document.body.classList.toggle('home-open',g.screen==='home');}
 this.updateHud();
 }
 updateHud(){const g=this.game;if(!g.started||g.blocked||g.settled){this.hud.innerHTML='';return;}const p=g.player,boss=g.boss,item=g.nearestItem(),ex=g.data.rooms[5].extraction,near=dist2(p,{x:ex[0],z:ex[2]})<2;let html='<div class="vitals"><span class="eyebrow">SABLE VOSS</span><div class="health-track"><i style="width:'+Math.max(0,p.hp/g.maxHP*100)+'%"></i></div><div class="vital-readout"><b>'+Math.max(0,p.hp)+' <small>/ '+g.maxHP+'</small></b><span>◈ '+g.scrap+'</span>'+(g.barrier?'<em>◇ '+g.barrier+'</em>':'')+'</div></div><div class="district"><span class="eyebrow">DEPTH '+g.depth+' / CYCLE '+g.cycle+'</span><h3>'+esc(g.data.rooms[g.roomIndex].title)+'</h3><small>'+CONDITIONS[g.condition]+'</small></div><div class="hud-menu">'+btn('page:pause','Ⅱ Menu')+'</div><div class="actionbar"><span><kbd>TAB</kbd> '+WEAPONS[g.weapon]+'</span><span><kbd>F</kbd> '+['Rupture','Stasis','Furnace'][g.skill]+' <b>'+(p.skillCD>0?Math.ceil(p.skillCD)+'s':'READY')+'</b></span><span><kbd>SPACE</kbd> Dash '+(p.dashCD>0?Math.ceil(p.dashCD)+'s':'')+'</span>'+btn('page:ledger','I · Build')+'</div>';
 if(boss?.hp>0)html+='<div class="boss-hud"><span>'+esc(boss.name.replace(/Body$/,'').replace(/([a-z])([A-Z])/g,'$1 $2'))+'</span><div class="health-track"><i style="width:'+Math.max(0,boss.hp/boss.maxHP*100)+'%"></i></div><small>'+boss.hp+' / '+boss.maxHP+(g.alive.some(e=>e.anchor)?' · ANCHORS SHIELD THE PONTIFF':'')+'</small></div>';
 if(boss?.hp<=0&&g.room===4)html+='<div class="context boss-choice"><span class="eyebrow">THE ENGINE IS UNSEALED</span><h3>Claim your memories. Or risk another descent.</h3><p><kbd>E</kbd> '+(near?'Extract now':'Approach the cyan engine to extract')+' &nbsp; <kbd>N</kbd> Descend to cycle '+(g.cycle+1)+'</p></div>';
 else if(item)html+='<div class="context"><kbd>E</kbd> '+['VENT PRESSURE','OVERLOAD CAPACITOR','SALVAGE CACHE','FABRICATE A RELIC · '+(10+3*(g.depth-1))+' SALVAGE','MEDICAL INJECTOR'][item.kind]+'</div>';
 for(const e of g.alive)if(!e.boss&&(e.visibleUntil>g.time||e.elite||e.anchor)){const pos=new THREE.Vector3(e.x,e.flying?1.9:e.anchor?1.4:2,e.z).project(this.world.camera);html+='<div class="enemy-bar" style="left:'+((pos.x*.5+.5)*100)+'%;top:'+((-pos.y*.5+.5)*100)+'%"><small>'+esc(TRAITS[e.affix]|| (e.anchor?'ANCHOR':''))+'</small><div><i style="width:'+Math.max(0,e.hp/e.maxHP*100)+'%"></i></div></div>';}
 this.hud.innerHTML=html;
 }
}
const dist2=(a,b)=>Math.hypot(a.x-b.x,a.z-b.z);
