import {THREE} from './assets.js';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {Reflector} from 'three/addons/objects/Reflector.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {clamp,dist,copy} from './rules.js';
const V=(p,y=.95)=>new THREE.Vector3(p.x,y,p.z),colors=[0x72e7f4,0x87f4ff,0xffc475,0xbb98ff,0xff6425,0x68f4f5];
export class World {
 constructor(canvas,assets,game){
  this.assets=assets;this.game=game;this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));this.renderer.info.autoReset=false;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFShadowMap;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.15;this.renderer.outputColorSpace=THREE.SRGBColorSpace;
  this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x081219);this.scene.fog=new THREE.FogExp2(0x152b31,.045);
  this.camera=new THREE.OrthographicCamera(-10,10,5.6,-5.6,.1,70);this.yaw=40*Math.PI/180;this.zoom=5.6;this.focus=new THREE.Vector3(0,.8,0);this.follow=true;this.raycaster=new THREE.Raycaster();this.ground=new THREE.Plane(new THREE.Vector3(0,1,0),-.16);this.pointer=new THREE.Vector2();
  const pmrem=new THREE.PMREMGenerator(this.renderer),env=new RoomEnvironment();this.scene.environment=pmrem.fromScene(env,.04).texture;env.dispose();pmrem.dispose();
  this.scene.add(new THREE.HemisphereLight(0xabcbd5,0x222324,1.05));
  const key=new THREE.DirectionalLight(0xb4d7e0,2.1);key.position.set(-6,12,5);key.castShadow=true;key.shadow.mapSize.set(2048,2048);Object.assign(key.shadow.camera,{left:-9,right:9,top:9,bottom:-9,near:1,far:30});key.shadow.bias=-.0006;key.shadow.normalBias=.03;this.scene.add(key);this.key=key;
  const rim=new THREE.DirectionalLight(0xc78443,1.3);rim.position.set(5,4,-6);this.scene.add(rim);
  this.composer=new EffectComposer(this.renderer);this.composer.addPass(new RenderPass(this.scene,this.camera));this.bloom=new UnrealBloomPass(new THREE.Vector2(1280,720),.28,.4,1.05);this.composer.addPass(this.bloom);this.composer.addPass(new OutputPass());
  this.rooms=new Map();this.entities=new Map();this.effects=[];this.dynamic=new THREE.Group();this.scene.add(this.dynamic);this.boltVisuals=new Map();this.warningVisuals=new Map();this.dropVisuals=new Map();this.fieldVisuals=new Map();this.numbers=[];this.elapsed=0;this.frame=0;
  this.hero=this.makeActor('SableVoss');this.scene.add(this.hero);this.hero.position.set(0,.16,2.75);const facing=this.hero.userData.nodes.find(n=>n.userData.originalName==='Facing');if(facing)facing.quaternion.identity();
  this.cursor=new THREE.Mesh(new THREE.RingGeometry(.12,.145,32),new THREE.MeshBasicMaterial({color:0x8ed5d2,transparent:true,opacity:.65,depthWrite:false}));this.cursor.rotation.x=-Math.PI/2;this.cursor.position.y=.18;this.scene.add(this.cursor);
  this.aura=new THREE.Mesh(new THREE.RingGeometry(.32,.345,48),new THREE.MeshBasicMaterial({color:0x76eadf,transparent:true,opacity:.6,depthWrite:false}));this.aura.rotation.x=-Math.PI/2;this.scene.add(this.aura);
  this.createAtmosphere();
  const reflector=new Reflector(new THREE.PlaneGeometry(9.65,8.4),{color:0x58666c,textureWidth:1024,textureHeight:1024,clipBias:.003,multisample:0});reflector.rotation.x=-Math.PI/2;reflector.position.y=.085;reflector.material.transparent=true;reflector.material.depthWrite=false;reflector.material.polygonOffset=true;reflector.material.polygonOffsetFactor=-1;
  reflector.material.vertexShader=reflector.material.vertexShader.replace('varying vec4 vUv;','varying vec4 vUv; varying vec2 surface;').replace('vUv = textureMatrix','surface = position.xy; vUv = textureMatrix');
  reflector.material.fragmentShader=reflector.material.fragmentShader.replace('varying vec4 vUv;','varying vec4 vUv; varying vec2 surface;').replace('gl_FragColor = vec4( blendOverlay( base.rgb, color ), 1.0 );','float puddle = sin(surface.x*1.7 + sin(surface.y*3.1))*.5+.5; float alpha = 0.12+puddle*0.24; vec3 reflected=base.rgb/(1.0+max(base.r,max(base.g,base.b))*.65)*.65; gl_FragColor=vec4(reflected*color,alpha);');
  this.reflector=reflector;this.scene.add(reflector);this.showRoom(0,false);this.resize();this.applyQuality();
 }
 makeActor(name){
  if(name==='NullAnchor'){const g=new THREE.Group(),m=new THREE.Mesh(new THREE.OctahedronGeometry(.35),new THREE.MeshStandardMaterial({color:0x9d5acd,emissive:0x9f4eea,emissiveIntensity:2,metalness:.7,roughness:.18}));m.position.y=.8;g.add(m);g.userData.anchor=m;return g;}
  const obj=this.assets.actor(name);obj.userData.mixer=new THREE.AnimationMixer(obj);obj.userData.actions=new Map();for(const c of obj.userData.clips)obj.userData.actions.set(c.name,obj.userData.mixer.clipAction(c));this.animate(obj,'idle',0);return obj;
 }
 animate(obj,state,dt,attackAge=99){
  const u=obj.userData;if(!u.mixer)return;const names=[...u.actions.keys()];let name;
  if(state==='dead')name=names.find(n=>/death/i.test(n));
  else if(attackAge<.36)name=names.find(n=>state==='slash'?/SwordSlash/i.test(n):state==='walk'||state==='run'?/WalkShoot/i.test(n):/QuickDraw|Attack/i.test(n));
  if(!name)name=state==='walk'||state==='run'?names.find(n=>state==='run'?/WraithRun|Running|Run$/i.test(n):/Walk/i.test(n)):names.find(n=>/Guard|Idle/i.test(n));
  name=name||names[0];if(name!==u.current){const next=u.actions.get(name);if(next){const old=u.actions.get(u.current);next.reset();next.setLoop(state==='dead'?THREE.LoopOnce:THREE.LoopRepeat,Infinity);next.clampWhenFinished=true;next.enabled=true;next.setEffectiveWeight(1);next.play();if(old)old.crossFadeTo(next,.16,false);}u.current=name;}
  u.mixer.update(dt);
 }
 showRoom(index,ready=true){
  for(const n of this.numbers)n.el.remove();this.numbers=[];if(this.room)this.scene.remove(this.room);if(!this.rooms.has(index))this.rooms.set(index,this.assets.room(index));this.room=this.rooms.get(index);this.scene.add(this.room);
  for(const o of this.entities.values())this.scene.remove(o);this.entities.clear();
  for(const maps of [this.boltVisuals,this.warningVisuals,this.dropVisuals,this.fieldVisuals]){for(const o of maps.values())this.disposeObject(o);maps.clear();}
  for(const e of this.effects)this.disposeObject(e.obj);this.effects=[];if(this.coverGroup){this.scene.remove(this.coverGroup);this.coverGroup.traverse(o=>{if(o.isMesh&&o.userData.localGeometry)o.geometry.dispose();});}
  this.coverGroup=new THREE.Group();this.scene.add(this.coverGroup);const colliders=this.room.userData.colliders.map(b=>({...b}));
  for(const c of ready?this.game.cover:[]){const obj=this.assets.actor(c.name);obj.rotation.y=c.yaw;obj.updateMatrixWorld(true);let b=new THREE.Box3().setFromObject(obj),size=b.getSize(new THREE.Vector3());const scale=Math.min(1.1/Math.max(size.x,size.z),1.45/size.y);obj.scale.multiplyScalar(scale);obj.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(obj);obj.position.set(c.x,.06-b.min.y,c.z);this.coverGroup.add(obj);obj.updateMatrixWorld(true);b=new THREE.Box3().setFromObject(obj);colliders.push({x0:b.min.x,x1:b.max.x,z0:b.min.z,z1:b.max.z});}
  this.focus.set(0,.8,0);this.hero.position.set(0,.16,2.75);this.hero.visible=true;
  if(ready)this.game.readyRoom(colliders,this.room.userData.interactables);this.resetAtmosphere();this.weapon();
 }
 weapon(){const w=this.game.started?this.game.weapon:0;for(const node of this.hero.userData.nodes){const n=node.userData.originalName;if(n==='Equipped Mourning Coil')node.visible=w===0;if(n==='Equipped Arc Saber')node.visible=w===1;for(const[i,name]of ['PressureScattergun','FuneralRail','CinderSprayer','TeslaLoom'].entries())if(n===name)node.visible=w===i+2;}}
 spawn(e){const o=this.makeActor(e.name);if(e.elite)o.scale.multiplyScalar(1.1);if(e.stationary&&e.name==='ArcTurret')o.scale.multiplyScalar(.65);o.position.set(e.x,e.flying?.85:.06,e.z);this.scene.add(o);this.entities.set(e.id,o);if(e.elite||e.affix){const ring=new THREE.Mesh(new THREE.RingGeometry(.34,.37,40),new THREE.MeshBasicMaterial({color:[0xae6fff,0x67e6ff,0xfac76a,0x76fcae,0xff8d55][e.affix],transparent:true,opacity:.7,depthWrite:false}));ring.rotation.x=-Math.PI/2;ring.position.y=.03;o.add(ring);}}
 resize(){const w=innerWidth,h=innerHeight;this.renderer.setSize(w,h);this.composer.setSize(w,h);this.camera.left=-this.zoom*w/h;this.camera.right=this.zoom*w/h;this.camera.top=this.zoom;this.camera.bottom=-this.zoom;this.camera.updateProjectionMatrix();}
 applyQuality(){const q=this.game.profile.settings.quality;this.renderer.setPixelRatio(Math.min(devicePixelRatio,q==='high'?1.5:q==='balanced'?1:.8));this.renderer.shadowMap.enabled=q!=='low';this.bloom.enabled=q!=='low';if(this.reflector)this.reflector.visible=q==='high';this.resize();}
 aim(clientX,clientY){this.pointer.set(clientX/innerWidth*2-1,-clientY/innerHeight*2+1);this.raycaster.setFromCamera(this.pointer,this.camera);const p=new THREE.Vector3();this.raycaster.ray.intersectPlane(this.ground,p);return{x:p.x,z:p.z};}
 moveVector(keys){const x=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),y=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0),right=new THREE.Vector3().setFromMatrixColumn(this.camera.matrixWorld,0),forward=new THREE.Vector3();this.camera.getWorldDirection(forward);forward.y=0;forward.normalize();const v=right.multiplyScalar(x).addScaledVector(forward,y);if(v.length()>1)v.normalize();return{x:v.x,z:v.z};}
 ring(radius,color,filled=false){const obj=new THREE.Group(),outline=new THREE.Mesh(new THREE.RingGeometry(Math.max(.01,radius-.035),radius,64),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.8,depthWrite:false,side:THREE.DoubleSide}));outline.rotation.x=-Math.PI/2;obj.add(outline);if(filled){const fill=new THREE.Mesh(new THREE.CircleGeometry(radius,64),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.12,depthWrite:false}));fill.rotation.x=-Math.PI/2;obj.add(fill);}return obj;}
 beam(from,to,weapon=0,crit=false){
  const color=crit?0xffd17c:colors[weapon],a=V(from),b=V(to),points=[a];
  if(weapon===5){for(let i=1;i<8;i++){const p=a.clone().lerp(b,i/8);p.x+=(Math.random()-.5)*.2;p.y+=(Math.random()-.5)*.16;p.z+=(Math.random()-.5)*.2;points.push(p);}}points.push(b);
  const curve=new THREE.CatmullRomCurve3(points),g=new THREE.TubeGeometry(curve,weapon===5?20:1,weapon===3?.042:.014,5,false),mat=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.95,blending:THREE.AdditiveBlending,depthWrite:false});const obj=new THREE.Mesh(g,mat);this.dynamic.add(obj);this.effects.push({obj,age:0,duration:weapon===5?.19:.13,fade:true});this.sparks(b,color,weapon===3?14:6);this.sparks(a,color,4);
 }
 shock(p,radius,color=0x72e7ed){const obj=this.ring(radius,color);obj.position.copy(V(p,.18));this.dynamic.add(obj);this.effects.push({obj,age:0,duration:.55,fade:true,expand:true});this.sparks(V(p,.25),color,16);}
 sparks(p,color,n=9){for(let i=0;i<n;i++){if(this.effects.length>220)break;const obj=new THREE.Mesh(this.sparkGeometry||(this.sparkGeometry=new THREE.OctahedronGeometry(.018)),new THREE.MeshBasicMaterial({color,transparent:true,blending:THREE.AdditiveBlending,depthWrite:false}));obj.position.copy(p);this.dynamic.add(obj);this.effects.push({obj,age:0,duration:.2+Math.random()*.25,fade:true,velocity:new THREE.Vector3((Math.random()-.5)*3,Math.random()*3,(Math.random()-.5)*3),sharedGeometry:true});}}
 attack(e){const {from,dir,weapon,range}=e;if(weapon===1){const obj=new THREE.Group();for(let n=0;n<3;n++){const g=new THREE.TorusGeometry(range*(.7+n*.12),.012+n*.009,4,48,Math.PI*.88),m=new THREE.MeshBasicMaterial({color:colors[1],transparent:true,opacity:.75,blending:THREE.AdditiveBlending,depthWrite:false});const arc=new THREE.Mesh(g,m);arc.rotation.x=-Math.PI/2;arc.rotation.z=-Math.PI*.44;obj.add(arc);}obj.position.copy(V(from,.8));obj.rotation.y=Math.atan2(dir.x,dir.z);this.dynamic.add(obj);this.effects.push({obj,age:0,duration:.25,fade:true});}
  else if(weapon===4){for(let i=0;i<12;i++){const t=Math.random(),a=(Math.random()-.5)*.6,dx=dir.x*Math.cos(a)-dir.z*Math.sin(a),dz=dir.x*Math.sin(a)+dir.z*Math.cos(a),end=this.game.nav.trace(from,{x:from.x+dx*range,z:from.z+dz*range}),obj=new THREE.Sprite(new THREE.SpriteMaterial({map:this.cloudTexture,color:i%3?0xff5a19:0xffd393,transparent:true,opacity:.8,blending:THREE.AdditiveBlending,depthWrite:false}));obj.position.set(from.x+(end.x-from.x)*t,.85+Math.random()*.35,from.z+(end.z-from.z)*t);obj.scale.setScalar(.2+t*.55);this.dynamic.add(obj);this.effects.push({obj,age:0,duration:.18+Math.random()*.16,fade:true,velocity:new THREE.Vector3(dx,1,dz)});}}
  else {const count=weapon===2&&!e.slug?5:1;for(let n=0;n<count;n++){const a=(n-(count-1)/2)*Math.PI/22,dx=dir.x*Math.cos(a)-dir.z*Math.sin(a),dz=dir.x*Math.sin(a)+dir.z*Math.cos(a);this.beam(from,this.game.nav.trace(from,{x:from.x+dx*range,z:from.z+dz*range}),weapon,e.crit);}}
 }
 event(e){if(e.type==='room')this.showRoom(e.index);if(e.type==='home')this.showRoom(0,false);if(e.type==='spawn')this.spawn(e.entity);if(e.type==='weapon')this.weapon();if(e.type==='beam')this.beam(e.from,e.to,e.weapon,e.crit);if(e.type==='attack')this.attack(e);if(e.type==='shock')this.shock(e,e.radius,e.color);if(e.type==='impact')this.sparks(V(e),e.critical?0xffd694:0x82c6d2,5);if(e.type==='dash')this.shock(e,.65,0x83d0ee);if(e.type==='shield')this.shock(e,.65,0xab68ed);
  if(e.type==='death'){const o=this.entities.get(e.entity.id);if(o){if(o.userData.clips?.some(c=>/death/i.test(c.name)))o.userData.dying=this.elapsed;else {this.scene.remove(o);o.userData.mixer?.stopAllAction();this.entities.delete(e.entity.id);}}this.sparks(V(e.entity,.7),0xffbc64,14);}
  if(e.type==='number'&&this.game.profile.settings.numbers){const el=document.createElement('span');el.className='damage '+(e.critical?'critical ':'')+(e.player?'injury':'');el.textContent=(e.player?'−':'')+e.damage;document.querySelector('#numbers').append(el);this.numbers.push({el,p:V(e,e.boss?2.7:1.65),age:0});}
 }
 createAtmosphere(){
  const c=document.createElement('canvas');c.width=c.height=64;const ctx=c.getContext('2d'),gradient=ctx.createRadialGradient(32,32,0,32,32,32);gradient.addColorStop(0,'rgba(255,255,255,.8)');gradient.addColorStop(.45,'rgba(255,255,255,.3)');gradient.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=gradient;ctx.fillRect(0,0,64,64);this.cloudTexture=new THREE.CanvasTexture(c);
  this.smoke=new THREE.Group();this.scene.add(this.smoke);this.smokeParticles=[];for(let i=0;i<36;i++){const o=new THREE.Sprite(new THREE.SpriteMaterial({map:this.cloudTexture,color:0x829ca3,transparent:true,opacity:.05,depthWrite:false}));this.smoke.add(o);this.smokeParticles.push({obj:o,phase:Math.random(),speed:.055+Math.random()*.08});}
  const points=new Float32Array(220*6);for(let i=0;i<220;i++){const k=i*6,x=Math.random()*18-9,y=Math.random()*10,z=Math.random()*16-8;points.set([x,y,z,x-.035,y-.35,z+.02],k);}this.rain=new THREE.LineSegments(new THREE.BufferGeometry().setAttribute('position',new THREE.BufferAttribute(points,3)),new THREE.LineBasicMaterial({color:0xa0c9cf,transparent:true,opacity:.18,depthWrite:false}));this.rain.frustumCulled=false;this.scene.add(this.rain);
 }
 resetAtmosphere(){const emit=this.room.userData.emitters;for(let i=0;i<this.smokeParticles.length;i++){const s=this.smokeParticles[i];s.source=emit.length?emit[i%emit.length]:{x:(i%6-2.5)*1.5,y:.2,z:(Math.floor(i/6)-2.5)*1.4};}}
 syncMap(map,list,create,update){const ids=new Set(list.map(e=>e.id));for(const[id,o]of map)if(!ids.has(id)){this.disposeObject(o);map.delete(id);}for(const e of list){if(!map.has(e.id)){const o=create(e);map.set(e.id,o);this.dynamic.add(o);}update(map.get(e.id),e);}}
 disposeObject(obj){obj.removeFromParent();obj.traverse(o=>{if(o.geometry&&o.geometry!==this.sparkGeometry&&!this.assets.geometry.includes(o.geometry))o.geometry.dispose();const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats)if(m&&!this.assets.materials.includes(m))m.dispose();});}
 update(dt,keys,input){
  this.renderer.info.reset();this.elapsed+=dt;this.frame++;const game=this.game,p=game.player,active=game.active,ambient=game.profile.settings.motion;
  if(active){this.yaw+=((keys.has('KeyQ')?-1:0)+(keys.has('KeyE')&&keys.has('AltLeft')?1:0))*dt*50*Math.PI/180;}
  const target=new THREE.Vector3(this.follow&&game.started?p.x*.35:0,.8,this.follow&&game.started?p.z*.35:0);if(!game.started&&ambient){target.x=this.pointer.x*.32;target.z=this.pointer.y*.18;}this.focus.lerp(target,1-Math.exp(-dt*5));
  this.camera.position.copy(this.focus).add(new THREE.Vector3(-Math.sin(this.yaw)*Math.cos(.698),Math.sin(.698),Math.cos(this.yaw)*Math.cos(.698)).multiplyScalar(18));this.camera.lookAt(this.focus);this.camera.updateMatrixWorld();
  this.hero.position.set(p.x,.16,p.z);const targetQ=new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),p.yaw||0);this.hero.quaternion.slerp(targetQ,Math.min(1,dt*16));const moving=p.move&&Math.hypot(p.move.x,p.move.z)>.1;
  this.animate(this.hero,p.hp<=0?'dead':game.weapon===1&&game.time-p.attackAt<.36?'slash':moving?(input.sprint?'run':'walk'):'idle',game.blocked&&game.started?0:dt,game.started?game.time-p.attackAt:99);
  this.cursor.visible=active;this.cursor.position.set(input.aim.x,.18,input.aim.z);this.aura.visible=game.started&&!game.settled;this.aura.position.set(p.x,.18,p.z);this.aura.material.color.set(game.barrier>0?0xa29aff:0x76eadf);
  for(const e of game.enemies){const o=this.entities.get(e.id);if(!o)continue;if(o.userData.dying!==undefined){this.animate(o,'dead',dt);if(this.elapsed-o.userData.dying>2.5){this.scene.remove(o);this.entities.delete(e.id);}continue;}o.position.set(e.x,e.flying?.85:.06,e.z);o.quaternion.slerp(new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0,1,0),e.yaw),Math.min(1,dt*8));if(o.userData.anchor){o.userData.anchor.rotation.y+=dt;o.userData.anchor.position.y=.8+Math.sin(this.elapsed*2)*.06;}this.animate(o,e.moving?'walk':'idle',active?dt:0,game.time-e.attackAt);}
  if(ambient){for(const m of this.room.userData.motions){const axis=new THREE.Vector3().fromArray(m.axis),t=this.elapsed+m.phase;if(m.kind===1)m.node.position.copy(m.position).addScaledVector(axis,Math.sin(t*m.speed)*m.amplitude);else m.node.quaternion.copy(m.rotation).multiply(new THREE.Quaternion().setFromAxisAngle(axis,-(m.kind===0?t*m.speed:Math.sin(t*m.speed)*m.amplitude)*Math.PI/180));}
   const a=this.rain.geometry.attributes.position;for(let i=0;i<a.count;i+=2){let y=a.getY(i)-dt*8;if(y<-.2)y=10;a.setY(i,y);a.setY(i+1,y-.35);}a.needsUpdate=true;
   for(const s of this.smokeParticles){s.phase=(s.phase+dt*s.speed)%1;const t=s.phase,v=s.source||{x:0,y:0,z:0};s.obj.position.set(v.x+Math.sin(t*4+v.x)*t*.4,v.y+t*2.2,v.z+Math.cos(t*3+v.z)*t*.4);s.obj.scale.setScalar(.4+t*1.65);s.obj.material.opacity=Math.sin(t*Math.PI)*.095;}
  }this.rain.visible=ambient;this.smoke.visible=ambient;
  this.syncMap(this.boltVisuals,game.bolts,()=>{const o=new THREE.Mesh(new THREE.SphereGeometry(.075,8,6),new THREE.MeshBasicMaterial({color:0xffa64e}));o.add(new THREE.PointLight(0xff853a,.8,1.3));return o;},(o,b)=>o.position.set(b.x,.95,b.z));
  this.syncMap(this.warningVisuals,game.warnings,w=>{if(w.kind==='aim'){const o=new THREE.Line(new THREE.BufferGeometry().setFromPoints([V(w.owner),V(w)]),new THREE.LineDashedMaterial({color:0xffba64,dashSize:.15,gapSize:.1,transparent:true,opacity:.5}));o.computeLineDistances();return o;}if(w.kind==='line'){const o=new THREE.Mesh(new THREE.PlaneGeometry(7.6,.84),new THREE.MeshBasicMaterial({color:0xdd81ff,transparent:true,opacity:.25,depthWrite:false}));o.rotation.x=-Math.PI/2;return o;}return this.ring(w.radius,w.kind==='boss'?0xffa057:0xffb852,true);},(o,w)=>{if(w.kind!=='aim')o.position.copy(V(w,.185));o.traverse(n=>{if(n.material)n.material.opacity=(n.isMesh&&n.geometry.type==='CircleGeometry'?.13:.65)+Math.sin((game.time-w.start)*12)*.08;});});
  this.syncMap(this.fieldVisuals,game.fields,f=>this.ring(f.radius,f.style===2?0xff6d27:0x8bb9fa,true),(o,f)=>{o.position.copy(V(f,.19));});
  this.syncMap(this.dropVisuals,game.drops,d=>{const obj=this.assets.actor(d.healing?'SoulVialPickup':'GearRelic');return obj;},(o,d)=>{o.position.set(d.x,.2+Math.sin(this.elapsed*3+d.id)*.07,d.z);o.rotation.y+=dt*.7;});
  for(let i=this.effects.length-1;i>=0;i--){const e=this.effects[i];e.age+=dt;const t=e.age/e.duration;if(t>=1){this.disposeObject(e.obj);this.effects.splice(i,1);continue;}if(e.velocity){e.obj.position.addScaledVector(e.velocity,dt);e.velocity.y-=dt*4;}if(e.expand)e.obj.scale.setScalar(.5+t*.5);if(e.fade)e.obj.traverse(o=>{if(o.material)o.material.opacity=(1-t)*.85;});}
  for(let i=this.numbers.length-1;i>=0;i--){const n=this.numbers[i];n.age+=dt;if(n.age>.8){n.el.remove();this.numbers.splice(i,1);continue;}const pos=n.p.clone();pos.y+=n.age*.7;pos.project(this.camera);n.el.style.transform='translate('+((pos.x*.5+.5)*innerWidth)+'px,'+((-pos.y*.5+.5)*innerHeight)+'px)';n.el.style.opacity=1-n.age/.8;}
  if(game.profile.settings.quality==='low')this.renderer.render(this.scene,this.camera);else this.composer.render();
 }
}
